### ISSUE TITLE
Uploading split apk mapping

### ISSUE THREAD

**Issue by rafagcamargo** [bugsnag/bugsnag-android-gradle-plugin#103]
### Expected behavior
Upload the correct mapping file according to the flavor and architecture.

### Observed behavior
`uploadBugsnagQa-armeabi-v7a-releaseMapping` task is uploading the wrong file. The project has three apks: `arm64-v8a`, `armeabi-v7a` and `universal`. Bugsnag plugin is always looking to `arm64-v8a` it does not matter which task you're calling, attached the log below.

### Steps to reproduce
Call `uploadBugsnagQa-armeabi-v7a-releaseMapping` and observe the logs by using the flags `-d`
`./gradlew :project:uploadBugsnagQa-armeabi-v7a-releaseMapping -d -S`

### Version
`3.2.5`

### Additional information
Logs:
```
16:30:44.869 [INFO] [org.gradle.api.Project] Found manifest at .../build/intermediates/manifests/full/qa/release/armeabi-v7a/AndroidManifest.xml
16:30:44.869 [DEBUG] [org.gradle.api.Project] Reading manifest at: .../build/intermediates/manifests/full/qa/release/armeabi-v7a/AndroidManifest.xml
16:30:44.889 [INFO] [org.gradle.api.Project] Attempting to upload mapping file: .../build/outputs/mapping/qa/release/arm64-v8a/mapping.txt
```

**Comment by fractalwrench** [comment]
Thanks for the report @rafagcamargo - would you be able to share some more details of your gradle configuration? I've tested the plugin using the following configuration, and observed the correct mapping file and build information for each variant - it would be good to understand how your project differs from this.

```
ext.abiCodes = ['arm64-v8a':2, armeabi:3, 'armeabi-v7a':4, mips:5, mips64:6, x86:7, 'x86_64':8]

android {
    splits {
        abi {
            enable true
            universalApk true
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def abiVersionCode =
                project.ext.abiCodes.get(output.getFilter("ABI"))

            if (abiVersionCode != null) {
                output.versionCodeOverride = abiVersionCode
            }
        }
    }
}

```

**Comment by rafagcamargo** [comment]
@fractalwrench thank you for replying it! Here's a few more details:
```
splits {
        // Configures screen ABI split settings
        abi {
            // Enable ABI APK splits
            enable true

            // By default all ABIs are included, so use reset() and include to specify that we only
            // want APKs for x86, armeabi-v7a, and mips

            // Resets the list of ABIs that Gradle should create APKs for to none
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for
            include "arm64-v8a", "armeabi-v7a"

            // Specify that we want to also generate a universal APK that includes all ABIs
            universalApk true
        }
    }
```
...
// Assign a unique version code for each architecture. The universal APK will have 0
```
ext.abiCodes = ["armeabi-v7a": 1, "arm64-v8a": 2]

import com.android.build.OutputFile

android.applicationVariants.all { variant ->
    if (variant.buildType.name == "release") {
        variant.outputs.all { output ->
            def baseAbiVersionCode = project.ext.abiCodes.get(output.getFilter(OutputFile.ABI))
            output.versionCodeOverride = variant.versionCode * 10 + (baseAbiVersionCode == null ? 0 : baseAbiVersionCode)
        }
    }
}
```

**Comment by rafagcamargo** [comment]
I've tried to remove `reset()` and `include "arm64-v8a", "armeabi-v7a"` from `abi {}` no success still.

**Comment by rafagcamargo** [comment]
I've tried to play with the order of 

`ext.abiCodes = ["armeabi-v7a": 1, "arm64-v8a": 2]` and `include "armeabi-v7a", "arm64-v8a"` keeping them in the same order, no success.

1. armeabi-v7a: uploadBugsnagQa-armeabi-v7a-releaseMapping
2. arm64-v8a: uploadBugsnagQa-arm64-v8a-releaseMapping
3. universal: uploadBugsnagQa-universal-releaseMapping

- uploadBugsnagQa-arm64-v8a-releaseMapping:

```
Found manifest at: .../build/intermediates/manifests/full/qa/release/arm64-v8a/AndroidManifest.xml
Reading manifest at: .../build/intermediates/manifests/full/qa/release/arm64-v8a/AndroidManifest.xml
Attempting to upload mapping file: .../build/outputs/mapping/qa/release/arm64-v8a/mapping.txt
```

- uploadBugsnagQa-universal-releaseMapping:

```
Found manifest at: .../build/intermediates/manifests/full/qa/release/universal/AndroidManifest.xml
Reading manifest at: .../build/intermediates/manifests/full/qa/release/universal/AndroidManifest.xml
Attempting to upload mapping file: .../build/outputs/mapping/qa/release/arm64-v8a/mapping.txt
```

- uploadBugsnagQa-armeabi-v7a-releaseMapping:

```
Found manifest at: .../build/intermediates/manifests/full/qa/release/armeabi-v7a/AndroidManifest.xml
Reading manifest at: .../build/intermediates/manifests/full/qa/release/armeabi-v7a/AndroidManifest.xml
Attempting to upload mapping file: .../build/outputs/mapping/qa/release/arm64-v8a/mapping.txt
```

**Comment by rafagcamargo** [comment]
Hello @fractalwrench, do you need extra information on this?

Thank you.

**Comment by fractalwrench** [comment]
Sorry for the delay @rafagcamargo - I've attempted to reproduce this using the [following sample case](https://github.com/bugsnag/bugsnag-android/tree/split-plugin-repro-case), and received the expected mapping file in both cases.

```
./gradlew build uploadBugsnagArm64-v8a-releaseMapping --info
Found manifest at /build/intermediates/manifests/full/release/arm64-v8a/AndroidManifest.xml
Attempting to upload mapping file: /build/outputs/mapping/release/mapping.txt
```

```
./gradlew build uploadBugsnagArmeabi-v7a-releaseMapping --info
Found manifest at /build/intermediates/manifests/full/release/armeabi-v7a/AndroidManifest.xml
Attempting to upload mapping file: /build/outputs/mapping/release/mapping.txt
```

This is using ProGuard - I will attempt the same with DexGuard and see if that makes a difference. Is the mapping file always located at `arm64-v8a` for you every time?

**Comment by rafagcamargo** [comment]
It seems DexGuard is making difference:
```
./gradlew clean assembleQaRelease uploadBugsnagQa-armeabi-v7a-releaseMapping --info

Task ':uploadBugsnagQa-armeabi-v7a-releaseMapping' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Filters: [FilterData{type=ABI, value=armeabi-v7a}]
OutputType: FULL_SPLIT
Found manifest at build/intermediates/manifests/full/qa/release/armeabi-v7a/AndroidManifest.xml
Attempting to upload mapping file: build/outputs/mapping/qa/release/arm64-v8a/mapping.txt
```

**Comment by fractalwrench** [comment]
Interesting - you can only observe the above behaviour when using DexGuard, rather than ProGuard? We're currently in the process of renewing our DexGuard license, so should be able to reproduce this fully once that's complete.

**Comment by fractalwrench** [comment]
Hi @rafagcamargo - we've managed to test this out and it seems to be an issue with DexGuard rather than the Bugsnag plugin.

I generated an empty project using Android Studio, integrated DexGuard, then added the following snippet and ran `./gradlew assemble`:

```
project.afterEvaluate {
    project.android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def assembleTask = project.tasks.findByName("assemble")
            assembleTask.doLast {
                println("Variant: $variant.name, Output: $output.name, Mapping File: $variant.mappingFile")
            }
        }
    }
}

```

The following output was received:

```
Variant: release, Output: arm64-v8a-release, Mapping File: /app/build/outputs/mapping/release/arm64-v8a/mapping.txt
Variant: release, Output: armeabi-v7a-release, Mapping File: /app/build/outputs/mapping/release/arm64-v8a/mapping.txt
Variant: release, Output: universal-release, Mapping File: /app/build/outputs/mapping/release/arm64-v8a/mapping.txt
```

I've forwarded this information onto GuardSquare so they can investigate the root cause. In the meantime I'll keep this issue open in case anyone else encounters the same issue.

**Comment by rafagcamargo** [comment]
@fractalwrench I've sent an email to DexGuard team, are you evaluating a possible change on bugsnag-plugin?

Thank you so much!

**Comment by rafagcamargo** [comment]
@fractalwrench I appreciate all your effort on this. Changing to productFlavor by ABI requires some work/complexity and one of reasons to integrate the plugin is to remove some of the complexity I have today due to manual upload. Considering you're willing to change the plugin I'm happy to wait for that.

Best,

**Comment by rafagcamargo** [comment]
@fractalwrench Are there any updates here?

Best,
Rafael.
