### ISSUE TITLE
Stack-trace de-obfuscation didn't work for library project

### ISSUE THREAD

**Issue by CAMOBAP795** [bugsnag/bugsnag-android-gradle-plugin#106]
### Expected behavior
 - Stack-trace must be de-obfuscated

### Observed behavior
 - I see obfuscated stack-trace on https://app.bugsnag.com

### Steps to reproduce
 - Create library project with single Class/method which throw exception
 - Integrate gradle plugin to this library project
   ```
	buildscript {
	    repositories {
	        maven {
	            url 'https://plugins.gradle.org/m2/'
	        }
	    }
	    dependencies {
	        classpath 'com.bugsnag:bugsnag-android-gradle-plugin:3.1.0'
	    }
	}
	apply plugin: 'com.bugsnag.android.gradle'

	android {
	    ...
	}

	...

	bugsnag {
	    apiKey 'XXX'
	    autoUpload false
	    retryCount 5
	}

   ```
 - Add library as dependency to the app
 - In app code call the method which throw exception

### Version
 - `3.1.0`

**Comment by fractalwrench** [comment]
Hi @CAMOBAP795 - I've had a look at your project and can see that 5 proguard mapping files have been uploaded, the most recent versionCode being 2611. I wasn't able to find Proguard mapping files for any of app versions in your recent Errors, which would explain why they were not deobfuscated.

I've also verified that Proguard upload works in a [library module](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/features/fixtures/app/module/config/android/default_lib.gradle), using an automated test runner. This was run against v3.2.5 of the plugin.

A few things will help us debug this further - can you see any messages from "uploadBugsnag" tasks in your gradle console output? It may be the case that an upload is timing out, or perhaps something is going wrong within the plugin.

It'd also be good to verify the gradle command you're using to upload the Proguard file, as I've noticed that you've disabled autoUpload. It'd also be good to see the config within your `android` block, particularly your Proguard configuration.

**Comment by fractalwrench** [comment]
>I didn't tried debug mode yet, but it always succeed, usually I use `./gradlew uploadBugsnagReleaseMapping` once release published

Would it be possible to see the gradle console output for this command?

>I think this is expected because our company delivers SDK (not apps). BTW Why it cannot work without app's maping.txt?

The mapping file contains the information required to deobfuscate a stacktrace, so if it hasn't been uploaded to Bugsnag, we won't be able to show the original stackframes. I think the next step from our side will be to check that deobfuscation works for the following scenarios:

- Library with proguard enabled
- App with proguard enabled, and also has the library AAR integrated

**Comment by fractalwrench** [comment]
I attempted to [reproduce this](https://github.com/bugsnag/bugsnag-android/compare/library-deobf-repro) using v3.2.5 of the plugin on a local Bugsnag instance, and observed the following deobfuscated stacktraces:

```
java.lang.RuntimeException
        at com.bugsnag.android.example.Foo.doAppCrash(Foo.java:11)
        at com.bugsnag.android.example.ExampleActivity$2.onClick(ExampleActivity.java:30)

java.lang.RuntimeException
        at com.bugsnag.android.lib.LibCrash.crashLib(LibCrash.java:6)
        at com.bugsnag.android.example.Foo.doLibraryCrash(Foo.java:7)
        at com.bugsnag.android.example.ExampleActivity$1.onClick(ExampleActivity.java:23)
```

I can see from your logs that the upload of the mapping file was successful. Would you be able to share the URL of an error which is obfuscated, and is known to use a version of the library with a versionCode of `2611`?

**Comment by CAMOBAP795** [comment]
> Would you be able to share the URL of an error which is obfuscated, and is known to use a version of the library with a versionCode of 2611?

Sure https://app.bugsnag.com/dial-once/sdk-android/errors/5ad5d386239af2001a5bf403 (I'm not sure how make it public or share)

**Comment by fractalwrench** [comment]
I continued with the [example project](https://github.com/bugsnag/bugsnag-android/compare/library-deobf-repro), and tried:

- Building an AAR directly from a library module with Bugsnag integrated, and confirming that the proguard mapping file was uploaded.
- Integrating the AAR into an app module with a _different versionCode_ to the library, then building a release APK.
- Performing a crash from within the library module, and within the app module.

Deobfuscation seemed to work for those scenarios, and the proguard file for each contained mappings for the library symbols in both cases. 

One thing I noticed is that (1) the Dial-Once AAR on Bintray is already obfuscated, and (2) the obfuscated stacktraces on your dashboard appear to be restricted to certain app packages. If the Dial-once SDK is integrated in an app that also has Proguard/Dexguard/R8 enabled, then I assume that could lead to the behaviour we're seeing, as the upload mapping file wouldn't match the symbol names.

Can I ask how often you see these obfuscated errors on average, and whether you know of any apps that don't use minification but still show obfuscated stacktraces?

**Comment by CAMOBAP795** [comment]
> One thing I noticed is that (1) the Dial-Once AAR on Bintray is already obfuscated

Yes, I can confirm this, we publishing obfuscated AAR on Bintray

> Can I ask how often you see these obfuscated errors on average, and whether you know of any apps that don't use minification but still show obfuscated stacktraces?

I think almost always, I didn't faced any deobfuscated stack-trace at this moment

> If the Dial-once SDK is integrated in an app that also has Proguard/Dexguard/R8 enabled, then I assume that could lead to the behaviour we're seeing, as the upload mapping file wouldn't match the symbol names.

Oh now I see the problem, .. well looks like in my case it's impossible to get de-obfuscated stack-traces, because I cannot force my clients to send mapping.txt (

@fractalwrench thanks for help, I think we may close this ticket
