### ISSUE TITLE
Gradle fails on BugsnagPlugin: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by marchello2000** [bugsnag/bugsnag-android-gradle-plugin#11]
@snmaynard / @loopj 
Hey guys, we are currently blocked by this issue. Followed all the directions to setup the plugin to upload proguard mapping but gradle fails with this error:
`java.lang.UnsupportedClassVersionError: com/bugsnag/android/gradle/BugsnagPlugin : Unsupported major.minor version 52.0`

Any suggestions?
Thanks!

**Comment by marchello2000** [comment]
Looks like the problem is that the plugin is compiled with Java 8

**Comment by loopj** [comment]
@marchello2000 well spotted - this is exactly the issue. Fixed in #12 and releasing as 2.0.1 now

**Comment by loopj** [comment]
Fixed and released as 2.0.1 - let me know if this fixes your issue!

https://search.maven.org/#artifactdetails%7Ccom.bugsnag%7Cbugsnag-android-gradle-plugin%7C2.0.1%7Cjar
https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v2.0.1
