### ISSUE TITLE
Plugin doesn't compile with Gradle Build Tools 3.1.2

### ISSUE THREAD

**Issue by CoreyAR** [bugsnag/bugsnag-android-gradle-plugin#111]
### Expected behavior
Gradle plugin works with Gradle build tools version 3.*

### Observed behavior
Building the Gradle build tools version 3.1.2 throws an error. 
```
> Manifest Tasks does not support the manifestOutputFile property any more, please use the manifestOutputDirectory instead.
  For more information, please check https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html

```

### Steps to reproduce
Try to compile the project with the bugsnag android gradle plugin and android gradle build tools 3.1.2

### Version
compileSdkVersion 26
com.bugsnag:bugsnag-android-gradle-plugin:2.+ -> 2.4.2

### Additional information
This is a react-native project using bugsnag-react-native version ~2.9.3.

**Comment by fractalwrench** [comment]
Thanks for your report @CoreyAR - version 3.0.0 and above of the Bugsnag Gradle Plugin support the Android Gradle Plugin 3.+. If you upgrade to the latest version then everything should work fine. If that's not the case, please let us know by commenting on the issue and we're happy to reopen it.
