### ISSUE TITLE
Does the upload API (or this plugin) support R8 mapping files?

### ISSUE THREAD

**Issue by ychescale9** [bugsnag/bugsnag-android-gradle-plugin#120]
Sorry this isn't directly related to the plugin but I ran into a couple of issues when using the `https://upload.bugsnag.com/` API to uploading `mapping.txt` generated by the R8 shrinker:

### Version
*Android Gradle Plugin 3.3-alpha04*

### Steps to reproduce
* Enable R8 in `gradle.properties` file: `android.enableR8=true`
* Enable proguard in `build.gradle`:
```
release {
  minifyEnabled true
  shrinkResources true
  proguardFiles('shrinker-rules.pro')
}
```
* Include `-keepattributes LineNumberTable, SourceFile` in the proguard configuration file
* Assemble the release APK: `./gradlew assembleRelease`
* Run the curl command to upload the mapping file:
```
curl https://upload.bugsnag.com/ \
              -F proguard=@app/build/outputs/mapping/r8/release/mapping.txt \
              -F apiKey=<API_KEY> \
              -F appId=<app.id> \
              -F versionCode=10000 \
              -F versionName=1.0.0 \
              -F overwrite=true
```

### Expected behavior
Upload successful.

#### 1. Invalid format
The first issue is that the upload API doesn't like mapping files with comments and responds with: `invalid format 1: # compiler: R8`

This can be fixed by removing the first few lines of comments in the `mapping.txt` file generated by R8.

#### 2. "proguard file generated without -keepattributes LineNumberTable"

As mentioned in the steps above `-keepattributes LineNumberTable, SourceFile` has been added to the proguard configuration file, but this error is still being reported, so I was wondering if the mapping file generated by R8 is supported by the upload API (or this gradle plugin)?

Thanks.

**Comment by fractalwrench** [comment]
Thanks for getting in touch @ychescale9 - it looks like our API isn't expecting comments at this position in a mapping file. I'll pass this onto our backend team who will find a fix for this issue, and we'll then perform some more compatibility testing to see if anything has changed compared to a ProGuard mapping file.

**Comment by AlecStrong** [comment]
With agp 3.2 release candidate out and a proper release coming soon, is there a timeline for this being released? We'd like to switch over to r8 with agp 3.2

**Comment by Pezzah** [comment]
We now support uploading R8 mapping files. However there is a open issue  [here](https://issuetracker.google.com/issues/112888094) which means that you need to use `proguard-android-optimize.txt` rather than `proguard-android.txt`.

**Comment by snmaynard** [comment]
Closing this issue as it's supported on our side now! Thanks for reporting @ychescale9.
