### ISSUE TITLE
creating NDK mapping file extremely slow

### ISSUE THREAD

**Issue by daviswalker** [bugsnag/bugsnag-android-gradle-plugin#123]
I am calling the "uploadBugsnagNdk" gradle task on my project, which contains a sizable NDK library. The built, stripped library is roughly 20MB. The debug library containing symbols - which is the one being processed by the plugin - is roughly 300MB in size. 

Running uploadBugsnagNdk on this library is extremely slow - it was still processing after 4 hours when I gave up and canceled. This is a function of objdump. Running the objdump command manually is just as slow. I have tried NDK versions 16b and 17 with the same result.

More specifically, the issue appears to be with the --line-numbers parameter. When I run "objdump --disassemble --demangle" and omit --line-numbers, objdump completes quickly.

This has not been an issue with other NDK crash reporting tools I have used. Is it possible to produce a mapping file for a large NDK library without the excessive delay?

Thank you.

Dave

**Comment by fractalwrench** [comment]
Thanks for the report @daviswalker - we're currently investigating the effects that removing `--linenumber` would have on the information available in stacktraces, and whether any alternatives that might increase performance.

**Comment by fractalwrench** [comment]
@daviswalker we've tested this out with a ~30Mb NDK library on macOS and didn't observe any obvious performance problems. Are you using Windows by any chance? We'd like to rule out the possibility that this could be platform-specific.

**Comment by daviswalker** [comment]
@fractalwrench Thank you for your response. We're on macOS. Might it be possible to share our library with you to see if this is a library difference or a toolchain difference? (Or perhaps you could share your test library with me)

**Comment by fractalwrench** [comment]
@daviswalker if you're willing to share your library with us that could be very helpful in tracking down the issue. If you could email support@bugsnag.com with the necessary information, I'll be happy to take a look.

**Comment by nick-joya** [comment]
@fractalwrench: I work with @daviswalker and have just emailed a link to our library.  As a further data point, in our attempts to work around the issue, we have been able to successfully and quickly dump symbols with line numbers using the LLVM version of objdump, demangled with c++filt.

`$ llvm-objdump -section=.text -line-numbers libfoo.so | c++filt -n > libfoo.map`

However, uploading this file to bugsnag simply returns the error: "Mapping file does not contain any functions".  I have included this file in my support email, as well.

**Comment by fractalwrench** [comment]
Thanks for the useful info @nick-joya - just to confirm are you building your project with GCC or Clang? I've passed the library onto my colleague @kattrali who is currently investigating performance improvements in this area.

**Comment by nick-joya** [comment]
Thanks, @fractalwrench!  We are building with clang.

**Comment by kattrali** [comment]
Thanks again, @nick-joya.
The slowness should be fixed in v3.4.0, however if there is an outstanding issue with GCC vs Clang toolchains, we should continue discussion in a new issue, to make sure it doesn't get lost.
