### ISSUE TITLE
mapping fail not uploaded but gradle task succeed

### ISSUE THREAD

**Issue by BraisGabin** [bugsnag/bugsnag-android-gradle-plugin#138]
### Expected behavior
If I run a command like `:app:uploadBugsnagProduction-releaseMapping` and it fails the task should fail.

### Observed behavior
I get a message that say that the upload failed:
> Bugsnag upload failed with code 400: proguard file generated without -keepattributes LineNumberTable
But the build succeed.

### Steps to reproduce
Proguard without `-keepattributes LineNumberTable` and try to upload the mapping manually.

### Version
4.5.0

### Additional information
This is a problem when you are running scripts or all your release is done by jenkins or similar.

**Comment by fractalwrench** [comment]
Thanks for the report @BraisGabin - this has now been addressed by #151
