### ISSUE TITLE
`sharedObjectPath` Does Not Respect Absolute Path

### ISSUE THREAD

**Issue by jamesonwilliams** [bugsnag/bugsnag-android-gradle-plugin#167]
I would like to supply an absolute path for the `sharedObjectPath` configuration value:

```groovy
// build.gradle
bugsnag {
    ..
    sharedObjectPath '/site/specific/abs/path'
    ..
}
```

However, the `BugsnagUploadNdkTask` [preprends the `projectDir.path`, via `new File(projectDir.path, sharedObjectPath)`](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/5a7534b57b9b23e1a0b0164ae30a092f257c9745/src/main/groovy/com/bugsnag/android/gradle/BugsnagUploadNdkTask.groovy#L70-L73).

Recall the behavior of the [`File(String parent, String child)` constructor](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#File(java.lang.String,%20java.lang.String)):
> If the `child` pathname string is absolute then it is converted into a relative pathname in a system-dependent way

Resultantly, if my `projectDir.path` is `/home/user/project`, the expression will end up as `/home/user/project/site/specific/abs/path`, instead of just `/site/specific/abs/path`.

**Comment by fractalwrench** [comment]
Thanks for getting in touch @jamesonwilliams - I can confirm that this looks like an issue with the plugin's API. As a workaround, it should be possible to relativize your sharedObjectPath using something like the following:

```
import java.nio.file.Path

Path absPath = new File("/usr/local").toPath()
Path relativePath = projectDir.toPath().relativize(absPath)
relativePath.toFile()

bugsnag {
    sharedObjectPath = relativePath.toFile().path
}
```

Longer-term, we're going to have a think about what the best way is to improve this API, and have created an internal ticket to track this. If you have any thoughts on this they'd very much be appreciated.
