### ISSUE TITLE
Plugin does not expand @string value for API_KEY

### ISSUE THREAD

**Issue by cwhenderson20** [bugsnag/bugsnag-android-gradle-plugin#183]
### Expected behavior
Upload release mapping task should expand the `@string` reference in the AndroidManifest file to represent the actual `API_KEY` value.

### Observed behavior
Upload release mapping task uses `@string/bugsnag_api_key` as the literal value for the `API_KEY`. This causes the upload to fail with error:

```
> Task :app:uploadBugsnagReleaseMapping
Attempting upload of mapping file to Bugsnag
Bugsnag upload failed with code 401: invalid apiKey

> Task :app:uploadBugsnagReleaseMapping FAILED

> Task :app:bugsnagReleaseReleaseTask
{"errors":["API key not recognised: @string/bugsnag_api_key"],"status":"error"}
Release Request failed with statusCode 400
```

### Steps to reproduce
Define bugsnag api key as a string resource:

**res/strings.xml**
```xml
<resources>
    <string name="bugsnag_api_key">API_KEY_HERE</string>
</resources>
```

Reference it in the AndroidManifest.xml file:

**AndroidManifest.xml**
```xml
<application>
    <meta-data
      android:name="com.bugsnag.android.API_KEY"
      android:value="@string/bugsnag_api_key" />
</application>
```

### Version
4.+

**Edit:**
I've realized after some research that this is likely not an issue with the plugin—the merged manifests are not pre-processed and thus do not contain the interpolated values (I'm not an Android developer by profession). However, using the above style _does_ allow the application to work at runtime. I'd prefer not to keep my API key directly in the manifest, so if there's an alternative, I'd love to know. Thanks!

**Comment by mattdyoung** [comment]
Hi @cwhenderson20 

The approach we'd recommend is described here:
https://docs.bugsnag.com/platforms/android/configuration-options/#customizing-by-build-setting

Using manifest placeholders in your app's `build.gradle` allows you to populate the Bugsnag API key (and other Bugsnag configuration) in the `AndroidManifest.xml` but vary the config for different build variants.

Thanks!

**Comment by MoNTE48** [comment]
Have the same issue.

> Task :app:bugsnagReleaseGoogle-releaseTask
{"errors":["API key not recognised: @string/bugsnag_api_key"],"status":"error"}
Release Request failed with statusCode 400

**Comment by xander-jones** [comment]
Hey @MoNTE48, if you make the following changes, this will fix the issue for you:
In your `AndroidManifest.xml`:
```
<application>
    <meta-data android:name="com.bugsnag.android.API_KEY" android:value="${bugsnagApiKey}"/>
...
```

In your `build.gradle`:
```
android {
    defaultConfig {
        manifestPlaceholders = [
            // omit any of the following placeholders to use the default values
            bugsnagApiKey: "<api-key>",
...
```

Take a look here for more information: https://docs.bugsnag.com/platforms/android/legacy/configuration-options/#manifest-placeholders. Re-opening and linking this to an internal ticket to track.

**Comment by MariaTod** [comment]
> Hey @MoNTE48, if you make the following changes, this will fix the issue for you:
> In your `AndroidManifest.xml`:
> 
> ```
> <application>
>     <meta-data android:name="com.bugsnag.android.API_KEY" android:value="${bugsnagApiKey}"/>
> ...
> ```
> 
> In your `build.gradle`:
> 
> ```
> android {
>     defaultConfig {
>         manifestPlaceholders = [bugsnagApiKey: "<api-key>"]
>     }
> }
> ...
> ```
> 
> Take a look here for more information: https://docs.bugsnag.com/platforms/android/legacy/configuration-options/#manifest-placeholders. Re-opening and linking this to an internal ticket to track.


I had the same error when I used "@string/bugsnag_api_key"
This one works!!
