### ISSUE TITLE
Readme links to "API docs" and "additional documentation" are broken

### ISSUE THREAD

**Issue by TheAlmightyBob** [bugsnag/bugsnag-android-gradle-plugin#184]
### Expected behavior
The links work.

### Observed behavior
The links go to a 404 page.

### Steps to reproduce
Click on "see the API docs" or "Additional Documentation"

### Version
N/A

### Additional information
The links are trying to go to https://bugsnag.com/docs/notifiers/android/proguard

**Comment by mattdyoung** [comment]
@TheAlmightyBob 
Thanks for pointing this out! We'll get the links fixed.

**Comment by mattdyoung** [comment]
Fixed by https://github.com/bugsnag/bugsnag-android-gradle-plugin/pull/187
