### ISSUE TITLE
Fails with AGP 4.1.0-alpha04

### ISSUE THREAD

**Issue by ZacSweers** [bugsnag/bugsnag-android-gradle-plugin#194]
### Expected behavior

No failure!

### Observed behavior

A breaking change causes a runtime failure

### Steps to reproduce

Checkout this commit: https://github.com/ZacSweers/CatchUp/tree/e40dccf76ff213ee1046e87fdc04366864bec248

Build: `./gradlew :app:processBugsnagXxxhdpiX86_64-debugManifest`

Observe this trace

```
Execution failed for task ':app:processBugsnagXxxhdpiX86_64-debugManifest'.
> Could not get unknown property 'manifestOutputDirectory' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.ProcessApplicationManifest.
```

### Version
4.7.4

**Comment by phillipsam** [comment]
Hi @ZacSweers - thanks for the report. Our gradle plugin does not yet support AGP 4.x. This is something on our roadmap to provide support for in the future.

**Comment by ZacSweers** [comment]
Makes sense. I do think this should be considered a bug rather hang a feature request, as this is an issue with the plug-in using private APIs

**Comment by ZacSweers** [comment]
The replacement API for this should be available in an upcoming AGP canary and will look like this:

```kotlin
android {
  onVariantProperties {
    val manifest: Provider<RegularFile> = operations.get(ArtifactTypes.MERGED_MANIFEST)
	// create own task and consume it
  }
}
```

**Comment by ZacSweers** [comment]
The AGP team has published an example of the replacement API here: https://github.com/android/gradle-recipes/blob/master/BuildSrc/manifestUpdaterTest/buildSrc/src/main/kotlin/ExamplePlugin.kt

Would you be open to a PR to use this now that AGP 4.1 is in beta? It is easy to gate its usage on the current AGP version so it wouldn't affect existing users, and allow users on newer version to begin testing for you. We currently have to disable bugsnag entirely to test newer AGP versions.

CC @fractalwrench

**Comment by fractalwrench** [comment]
Hi Zac, we'd be open to a PR on this if it would maintain backwards compatibility. I'm in the process of planning some other general improvements to this gradle plugin so should be able to help get anything over the line.

**Comment by ZacSweers** [comment]
This is fixed on the v5 branch now 👍

**Comment by rovkinmax** [comment]
@ZacSweers How I can use v5?

**Comment by mattdyoung** [comment]
Now released:
https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases
