### ISSUE TITLE
How to set overwrite == true?

### ISSUE THREAD

**Issue by fcduarte** [bugsnag/bugsnag-android-gradle-plugin#24]
Hi guys,

I saw that here:

https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/baeee1893e63eeed29cdd27639c3bbce39f8fb35/src/main/groovy/com/bugsnag/android/gradle/BugsnagUploadTask.groovy#L87

there's a `bugsnag.overwrite` property. How can I set it during build time?

Thanks!

**Comment by kattrali** [comment]
Closed via 63e999c03aa2ebdf5319a132c87aec3bf3580fb0. Thanks again!
