### ISSUE TITLE
Allow disabling "auto upload" for proguard-enabled builds

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-android-gradle-plugin#3]
We should allow people to disable the "auto upload" feature, and choose to enable mapping file uploading on a "per release type" basis.

**Comment by RobBlairInq** [comment]
Agreed.  Dev builds should not spam servers, but we still need to run builds in obfuscated modes to make sure things work.

There may be some clever gradle options to help control this, will have to play around.

**Comment by loopj** [comment]
This will be address in #10

**Comment by loopj** [comment]
Hey all, this fix has been released in 2.0.0 of the plugin, should be hitting maven central soon, thanks for all the help!
