### ISSUE TITLE
BugsnagInstallJniLibsTask setup should be moved to different plugin class so it can be applied to android library module

### ISSUE THREAD

**Issue by pbajurko** [bugsnag/bugsnag-android-gradle-plugin#309]
With fixes in version 5.1.0 we were able to integrate v5 plugin though some regressions were spotted.

1. In version 5 of plugin support for library modules [was dropped](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/src/main/kotlin/com/bugsnag/android/gradle/BugsnagPlugin.kt#L52). While it make sense to require this for variant based configuration, the BugsnagInstallJniLibsTask should be allowed to be added at any level. 

2. It's not clear why would BugsnagInstallJniLibsTask setup depend on [uploading NDK symbols](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/src/main/kotlin/com/bugsnag/android/gradle/BugsnagPlugin.kt#L145) while we just need it for compilation. E.g. explicitly setting `bugsnag.uploadNdkMappings` to false will [disable BugsnagInstallJniLibsTask setup](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/src/main/kotlin/com/bugsnag/android/gradle/BugsnagPlugin.kt#L404).

So we would like to see BugsnagInstallJniLibsTask setup moved to different plugin class so it can be applied to android library module.

**Comment by johnkiely1** [comment]
Hi @pbajurko,

Adding support for library modules is on our roadmap. Although we don't have any confirmed timeframes for this as yet. 

The BugsnagInstallJniLibsTask copies the JNI libraries and is usually only required if you are linking against Bugsnag's SO files. Are you using [Bugsnag's NDK API](https://docs.bugsnag.com/platforms/android/#native-api-configuration), perhaps you could explain your use case for doing this? Separating out this from the the upload task could mean the symbols then are not uploaded. Is there a reason you would not want to upload the symbols for your use case?

**Comment by pbajurko** [comment]
Hey @johnkiely1, 

> Are you using Bugsnag's NDK API, perhaps you could explain your use case for doing this?

e.g. https://github.com/bugsnag/bugsnag-android/issues/904#issuecomment-663687119

> Is there a reason you would not want to upload the symbols for your use case?

It's rather simply in daily development we want to compile app without need to upload symbols. We can do it with SDK API but not NDK API for some reason(?). Also we want keep Bugsnag related code at library level for better modularity we can do it with SDK API but not NDK's one.

So it's rather simply change just please move BugsnagInstallJniLibsTask setup to different plugin class that can be applied to library as it [was in version 4 of plugin](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/v4.7.5/src/main/groovy/com/bugsnag/android/gradle/BugsnagPlugin.groovy#L61)

**Comment by johnkiely1** [comment]
Hi @pbajurko,

Thanks for that. It seems pretty reasonable, so we are going to look into making this change back to something like how it was in v4. I will let you know of any updates.

**Comment by phillipsam** [comment]
@pbajurko we have now released a new version of our Gradle plugin [v5.3.0](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v5.3.0) which should fix this issue.

**Comment by pbajurko** [comment]
@phillipsam thanks although it #323 fixes only one from listed regressions.

NDK dependencies still can only at application module [level](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/src/main/kotlin/com/bugsnag/android/gradle/BugsnagPlugin.kt#L54) not library one like it was in v4

**Comment by johnkiely1** [comment]
Hi @pbajurko,

Prior to v5 this worked in some circumstances although it was never officially supported by us. In v5 using a later version of AGP meant this didn't work anymore. Adding back in the library module support is on the roadmap as we do want to officially support it but it does require more work. To that end I have reopened this ticket, and will let you know of any updates.

**Comment by pbajurko** [comment]
@johnkiely1 

As mentioned in original post, we don't need main plugin class to support library modules.
What we need is just task that will deliver native dependencies on library level and this can be done in separate plugin class.

Also not sure why this plugin has this responsibility, they coming from https://github.com/bugsnag/bugsnag-android/blob/master/bugsnag-plugin-android-ndk. So they should be distributed there? Also you mention newer AGP version which supports [native dependencies from aars](https://developer.android.com/studio/build/native-dependencies) so maybe simply publish them next to SDK's AAR?

**Comment by johnkiely1** [comment]
Thanks for the suggestions. 
At this stage we are happy with the structure of plugin and splitting it out to that level of granularity could become confusing. While you are waiting for us to implement library module support, you could by all means write your own gradle task to copy the files in to the library module or indeed adapt ours to your requirements. 

Putting NDK dependencies into the AAR is something that we are considering and do have this on our roadmap.

**Comment by mattdyoung** [comment]
We've released a further fix in [v7.1.0](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v7.1.0) which covers this case.
