### ISSUE TITLE
Building APK and App Bundle in the same command fails

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [bugsnag/bugsnag-android-gradle-plugin#322]
### Describe the bug
Here, we generate the APK and App Bundle in the same gradle command and by doing that on Bugsnag plugin above 5.0.0, causes the build to fail.

### Steps to reproduce
To simulate is simple: just run `./gradlew app:bundleRelease app:assembleRelease`, both of the tasks in the same gradle command. If I run them separately, the bug doesn't occur.

### Environment
* Android Studio version: 4.0.1
* Android Gradle version: 4.0.1

### Example code snippet 

```
implementation com.bugsnag:bugsnag-android-gradle-plugin:5.2.0
```

<details><summary>Error messages:</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processBugsnagReleaseManifest'.
> Unexpected number of manifest paths.[/Users/guilherme.pereira/Documents/Projects/ifood-consumer-android/app/build/intermediates/merged_manifests/release/AndroidManifest.xml, /Users/guilherme.pereira/Documents/Projects/ifood-consumer-android/app/build/intermediates/bundle_manifest/release/bundle-manifest/AndroidManifest.xml]
```
</details>

**Comment by mattdyoung** [comment]
Thanks for reporting. We're looking into a fix.

**Comment by fractalwrench** [comment]
Hi @guilherme-pereira-ifood - thanks for reporting this. I believe @mattdyoung has already recommended upgrading to Android Gradle Plugin 4.1.0 which should resolve the issue, but would be interested to know what your use-case is for building an App Bundle and APK at the same time.

In versions of the Android Gradle Plugin below 4.1.0 there is not a suitable API for plugins to manipulate the AndroidManifest.xml, so the Bugsnag Android Gradle Plugin has to guess the location of the AndroidManifest.xml file. This isn't a scenario we've anticipated so it'd be great to get some feedback on how you use the APK and App Bundle in your build process.

As Matt has mentioned, upgrading to AGP 4.1.0 should workaround the issue, as would running the two builds as separate tasks: `./gradlew app:bundleRelease && ./gradlew app:assembleRelease`

**Comment by guilherme-pereira-ifood** [comment]
Unfortunately this AGP 4.1.0 is not stable yet, that's why we haven't updated yet.

Our use-case is: on the release day, we build the app bundle to send to the store and we build the APK to send to an internal testing program in the company. This are made by Jenkins pipelines.

I think your suggestion may work, running them separately with `&&`. I'll change our Jenkins pipeline and see if that works, considering the way the devops team developed our Jenkinsfile.

**Comment by guilherme-pereira-ifood** [comment]
AGP 4.1 is now stable and after upgrading to it, the reported issue does't happen anymore.

Thanks for the suggestion, @fractalwrench !

Suggestion: Maybe it's worth adding this info on a troubleshooting page.

**Comment by phillipsam** [comment]
Closing as this is no longer an issue with AGP 4.1.0
