### ISSUE TITLE
Crash stack trace has the title obfuscated

### ISSUE THREAD

**Issue by MariaTod** [bugsnag/bugsnag-android-gradle-plugin#324]
<img width="1357" alt="bugsnag crash log" src="https://user-images.githubusercontent.com/13196535/95859927-036a7380-0d68-11eb-9382-484811ba220c.png">

### Describe the bug
I've integrated Bugsnag gradle in my Android application and the title of the crash stack trace is still obfuscated.
The actual crash stack trace it's de-obfuscated so it's correct, as you can see in the screenshot from Bugsnag that I've attached.

Is this intended or it's a bug on your side?

Is there some extra setup that I should do to fix this?

### Versions
bugsnag-android-gradle-plugin:5.2.0
 Android Gradle Plugin 3.6.4

**Comment by mattdyoung** [comment]
Hi @MariaTod 

The "title" you describe is actually the error message of the Throwable. It's not currently possible to deobfuscate the references like this within the error message itself.

This is already being considered under https://github.com/bugsnag/bugsnag-android/issues/932
