### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by saantiaguilera** [bugsnag/bugsnag-android-gradle-plugin#35]
When having multiple apks (because we have density/arch splits), bugsnag is only uploading the mappings for the `universal.apk` and not for the splitted ones.

How can we achieve this ? (I tried to do a PR with the changes but im not quite sure how do you differentiate one apk from another for the maps)

**Comment by fractalwrench** [comment]
Split support is partially addressed by #52 - we may need to make a couple of API changes to complete this one.

**Comment by fractalwrench** [comment]
#52
