### ISSUE TITLE
versionCode is always resolved at configuration time

### ISSUE THREAD

**Issue by ZacSweers** [bugsnag/bugsnag-android-gradle-plugin#384]
### Describe the bug
the `versionCode` property is always resolved at configuration time. This is expensive as it could very well be computed by a task, meaning this is now executing a task at configuration time

https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/src/main/kotlin/com/bugsnag/android/gradle/BugsnagPlugin.kt#L649

It should try to use the newer property-based API output API to avoid this on newer AGP versions where possible

### Steps to reproduce
All the details are above. Reproduction is easy - set a custom version code mapped from a gradle property. In our case we do it from an env var on CI.

### Environment
* Android Studio version: N/A
* Android Gradle version: 7
* Bugsnag manifest section (if modified): N/A

**Comment by yousif-bugsnag** [comment]
Thanks for raising this @ZacSweers - we'll look into this as soon as priorities allow

**Comment by lemnik** [comment]
Hi @ZacSweers

We recently made some changes for v7.1.0 of the plugin which should solve this issue. Please re-open if it's still a problem and we'll take another look.
