### ISSUE TITLE
Unable to sync with android gradle plugin alpha4

### ISSUE THREAD

**Issue by tylergets** [bugsnag/bugsnag-android-gradle-plugin#39]
Hey guys; love the product.  We recently upgraded to gradle 4.0 and had little problems with the bugsnag plugin, however it appears the latest android gradle plugin "alpha4" breaks the plugin.

We receive the following error when trying to sync:

```
Error:Could not get unknown property 'textSymbolOutputDir' for task ':MedaCheck:processMedacheckReleaseResources' of type com.android.build.gradle.tasks.ProcessAndroidResources.
```

**Comment by kattrali** [comment]
Thank you for the report, @tylergets. It looks like we'll need to update the plugin to account for what's changed in `ProcessAndroidResources`. 🤔

**Comment by fractalwrench** [comment]
More details in #40
