### ISSUE TITLE
Update docs to reflect new UUID + proguard settings magic

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-android-gradle-plugin#4]
- Explain how our UUID stuff works
- Remove notes about failed uploads due to duplicate proguard files, shouldn't happen anymore with new UUID system
- Remove notes about "proguard configuration" since we automatically add `-keepattributes` stuff now

**Comment by snmaynard** [comment]
Proguard configuration is still there?

**Comment by ConradIrwin** [comment]
Yeah, I left it there because it explains what the plugin changes about your build process. We could use a different heading that makes it clearer that it's just purely informational, but I couldn't think of one.
