### ISSUE TITLE
Applying plugin to 'com.android.library' project

### ISSUE THREAD

**Issue by CAMOBAP795** [bugsnag/bugsnag-android-gradle-plugin#41]
### Problem
According current implementation `bugsnag` can not be applied to 'com.android.library' project
https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/master/src/main/groovy/com/bugsnag/android/gradle/BugsnagPlugin.groovy#L34

### Expected behavior
It will be nice if `bugsnag` plugin can be integrated in 'com.android.library' project

I can proceed with PR preparation if there is no objections

**Comment by jkernech** [comment]
Any update on this issue ?

**Comment by fractalwrench** [comment]
Released in v3.1.0

**Comment by CAMOBAP795** [comment]
I just noticed that stack-trace de-obfuscation didn't work for library project.

@fractalwrench may you check this? Also is there a way to check uploaded `mapping.txt` on `https://app.bugsnag.com`?

**Comment by fractalwrench** [comment]
@CAMOBAP795 can you open a separate issue with details on your gradle configuration, and plugin version? I can investigate using that information.

It's not currently possible for regular users to check uploaded mapping files.

**Comment by CAMOBAP795** [comment]
@fractalwrench sure, thanks https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/106
