### ISSUE TITLE
React native app bundle fails with new 5.8.0 plugin

### ISSUE THREAD

**Issue by stefkampen** [bugsnag/bugsnag-android-gradle-plugin#438]
After the release of the 5.8.0 the android builds of my react native apps started failing.
Builds are using the Gradle bundle command to create an .aab file.

The error is:
> Task :app:bugsnagRelease****-releaseTask
> Bugsnag: Uploading to Releases API
> Task :app:generateBugsnag****-releaseMapping FAILED
> FAILURE: Build failed with an exception.
> * What went wrong:
> Execution failed for task ':app:generateBugsnag****-releaseMapping'.
> Expected file collection to contain exactly one file, however, it contains no files.

### Environment
* Latest android studio
* Gradle plugin 3.5.3

Please let me know if you need any additional information. For now I have reverted to 5.7.8 to resolve the issue.

**Comment by xander-jones** [comment]
Hey @stefkampen, thanks for reporting this. If you could you please re-run this build with the `./gradlew YOUR_BUILD_NAME_AND_PARAMS --info --stacktrace` Gradle options to get a more detailed output, that would be greatly appreciated!

**Comment by tommeier** [comment]
also failing for us in similar ways, we've locked down to `5.7.8` and builds have started working again.

Our symptom was `react-native-config` would no longer read the env values used for the API key for bugsnag (or any resources).

**Comment by xander-jones** [comment]
Hey @stefkampen & @tommeier, this can be recreated by using AGP 3.5.3 and turning the Java obfuscation on (it’s off by default in React Native projects). We suspect it's a task ordering issue. We'll take a look into this, but pinning to v5.7.8 for now should do the trick!

**Comment by stefkampen** [comment]
Thanks. Yes we have it turned on.

**Comment by tommeier** [comment]
great thanks @xander-jones - this is our exact issue over here: https://github.com/bugsnag/bugsnag-android-gradle-plugin/issues/442#issue-1003418074 - we're on a later AGP, good luck on the bug hunt 👍

**Comment by johnkiely1** [comment]
Hi @stefkampen, @tommeier 

This should now be fixed in [v5.8.1](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v5.8.1). Let us know if you have any issues with it.
