### ISSUE TITLE
Bugsnag Gradle plugin fails to generate NDK mapping files since NDK r23

### ISSUE THREAD

**Issue by vmilea** [bugsnag/bugsnag-android-gradle-plugin#456]
### Describe the bug

NDK r23 has removed GNU binutils:

```
find . -iname "*objdump"

./22.1.7171670/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-objdump
./22.1.7171670/toolchains/x86-4.9/prebuilt/darwin-x86_64/i686-linux-android/bin/objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/aarch64-linux-android/bin/objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android-objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android-objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/arm-linux-androideabi/bin/objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/objdump
./22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/i686-linux-android/bin/objdump
./22.1.7171670/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/bin/x86_64-linux-android-objdump
./22.1.7171670/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/x86_64-linux-android/bin/objdump
./22.1.7171670/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-objdump
./22.1.7171670/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/arm-linux-androideabi/bin/objdump
./22.1.7171670/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/aarch64-linux-android/bin/objdump
./22.1.7171670/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-objdump

./23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-objdump
```

The Bugsnag Android plugin can't cope, and fails when preparing symbols:

```
> Task :app:generateBugsnagNdkPlay-releaseMapping
Generating NDK mapping files
Bugsnag: Error attempting to calculate objdump location: Failed to find executable objdump at /Users/vmilea/Library/Android/sdk/ndk/23.1.7779620/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-objdump
Bugsnag: Unable to upload NDK symbols: Could not find objdump location for arm64-v8a
Bugsnag: Error attempting to calculate objdump location: Failed to find executable objdump at /Users/vmilea/Library/Android/sdk/ndk/23.1.7779620/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-objdump
Bugsnag: Unable to upload NDK symbols: Could not find objdump location for arm64-v8a
...
```

### Steps to reproduce
1. Set `ndkVersion 23.1.7779620`
2. Do a release build.

### Environment
* Android Studio version: Android Studio Bumblebee | 2021.1.1
* Gradle version: 7.0.2
* Android Gradle Plugin (AGP) version: 7.0.4
* Bugsnag Android Gradle Plugin version: 7.2.0
* Bugsnag manifest section (if modified): -

**Comment by xander-jones** [comment]
Hey @vmilea, thanks for raising this issue. Yes, looks like the `objdump` binaries were indeed removed in NDK r23. We'll take a look into what's possible to support this version here. In the meantime, if you're able to NDK r21 still contains these binaries and is tested with.

**Comment by johnkiely1** [comment]
Hi @vmilea, 
Thanks for the suggestion, we are looking into the approach of processing on server and we will let you know of updates. 
In the meantime your workaround seems like the best option here.

**Comment by jgreen210** [comment]
We didn't notice this problem for a long time since it just logs some errors, it doesn't make the gradle tasks fail.

**Comment by luke-belton** [comment]
Hi @jaltin - this is still on our backlog to review when priorities allow. In the meantime, you could consider adopting the workaround suggested above.

**Comment by jaltin** [comment]
> Hi @jaltin - this is still on our backlog to review when priorities allow. In the meantime, you could consider adopting the workaround suggested above.

@luke-belton we have avoided the fix as it caused other complications for us. 

Do you have any idea of if/when this will be looked at?

**Comment by phillipsam** [comment]
@jaltin this is one of the things that we are looking into at the moment. It requires a fair amount of work and we are hoping to release something for this in the next quarter.

**Comment by jaltin** [comment]
> @jaltin this is one of the things that we are looking into at the moment. It requires a fair amount of work and we are hoping to release something for this in the next quarter.

@phillipsam Thanks for the more time specific update, it really helps in setting our expectations.

Hope you manage to get it done in the next quarter, would really be helpful.

**Comment by afturner** [comment]
Hi @phillipsam, just wanted to check in and see whether there were any updates on the plan for working on a fix? Just curious :) thanks.

**Comment by johnkiely1** [comment]
Hey @afturner, This is still on our backlog, and has turned into an even larger piece of work that initially expected. We are working on some of the prerequisites at the moment and expect get to this soon, but we don't have any updated ETA to share at the moment.

**Comment by gareththackeray** [comment]
As of version [7.4.0](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v7.4.0) this plugin you can opt in to our new mechanism for uploading symbols files by setting the `useLegacyNdkSymbolUpload` config to `false`.

For more information see [the docs](https://docs.bugsnag.com/build-integrations/gradle/#ndk-symbol-files). Any issues please let us know.

**Comment by optinify-andrei** [comment]
We still have not seen the NDK symbols files being uploaded using the 7.4.0 version configured using the guide.
I see this message in the log output:
```
[10:27:26]: ▸ [35mCannot detect Bugsnag SDK version for variant prodRelease, assuming a modern version is being used. This can cause problems with NDK symbols if older versions are being used. Please either specify the Bugsnag SDK version for prodRelease directly.See https://docs.bugsnag.com/api/ndk-symbol-mapping-upload/ for details.[0m
```

Is this the source of the issue and if so how we can fix it?

**Comment by andrei-tofan** [comment]
We still have not seen the NDK symbols files being uploaded using the 7.4.0 version configured using the guide.
I see this message in the log output:

```
Cannot detect Bugsnag SDK version for variant prodRelease, assuming a modern version is being used. This can cause problems with NDK symbols if older versions are being used. Please either specify the Bugsnag SDK version for prodRelease directly.See https://docs.bugsnag.com/api/ndk-symbol-mapping-upload/ for details.
```

Is this the source of the issue and if so how we can fix it?

**Comment by johnkiely1** [comment]
HI @andrei-tofan, would you mind writing in to us at support@bugsnag.com. If you would be willing to share your entire `build.gradle` files that would be ideal. If thats not possible at a minimum could you include how you are configuring the BugSnag gradle plugin in your `build.gradle` files.

**Comment by andrei-tofan** [comment]
Hi @johnkiely1, I've sent the files to support (request [#43575](https://bugsnag.zendesk.com/hc/requests/43575)).
