### ISSUE TITLE
AGP 7.2.0 not supported

### ISSUE THREAD

**Issue by akoell** [bugsnag/bugsnag-android-gradle-plugin#462]
### Describe the bug

Build failure with AGP 7.2.0

### Steps to reproduce
Upgrade to AGP 7.2.0 and run a release task

### Environment
* Android Studio version: Chipmunk
* Gradle version: 7.4.2
* Android Gradle Plugin (AGP) version: 7.2.0
* Bugsnag Android Gradle Plugin version: 7.2.0

```
java.lang.NoSuchMethodError: 'java.io.File com.android.build.gradle.tasks.ExternalNativeBuildTask.getObjFolder()'
	at com.bugsnag.android.gradle.BugsnagPlugin$registerReleasesUploadTask$1$$special$$inlined$forEach$lambda$1.transform(BugsnagPlugin.kt:699)
	at com.bugsnag.android.gradle.BugsnagPlugin$registerReleasesUploadTask$1$$special$$inlined$forEach$lambda$1.transform(BugsnagPlugin.kt:67)
```

Cause is a changed API in `ExternalNativeBuildTask` where previously `objFolder` & `soFolder` returned a `File` it now returns a `DirectoryProperty`

Diff:
https://android.googlesource.com/platform/tools/base/+/ff92a1c5fe15aa34c294044f358fcc9b39e19f8b%5E%21/#F13

**Comment by yousif-bugsnag** [comment]
This is now fixed in [v7.2.1](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v7.2.1)
