### ISSUE TITLE
Source control is not automatically integrated

### ISSUE THREAD

**Issue by alexzaitsev** [bugsnag/bugsnag-android-gradle-plugin#488]
### Describe the bug
First of all, I need to understand does this plugin supports linking to private repos? My repo is private, bugsnag is working properly and for long period of time already. Now we need to extend it to link stacktraces to source control. 
My config:
1. root 
```
buildscript {
    dependencies {
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:7.0.0-beta01"
   }
}
```
2. app module
```
plugins {
     id 'com.bugsnag.android.gradle'
}

android {
    // ....
     bugsnag {
        sourceControl {
            repository = "https://github.com/unstoppabledomains/domains-manager-android"
        }
    }
}
```
I also tried to add provider and commit hash but still the same result. Need your help.

### Environment
* Android Studio version: `Build #AI-213.7172.25.2113.9123335, built on September 30, 2022`
* Gradle version: 
* Android Gradle Plugin (AGP) version: `classpath 'com.android.tools.build:gradle:7.3.1'`
* Bugsnag Android Gradle Plugin version: `classpath "com.bugsnag:bugsnag-android-gradle-plugin:7.0.0-beta01"`
* Bugsnag manifest section (if modified): no

**Comment by johnkiely1** [comment]
Hi @alexzaitsev Not sure if you've seen the above, but we could do with some additional information in order to investigate any further. Closing this for now as we have not heard from you but happy to reopen as necessary.
