### ISSUE TITLE
How can I check a successful upload and match?

### ISSUE THREAD

**Issue by cemo** [bugsnag/bugsnag-android-gradle-plugin#5]
I would like to be sure that my application has a necessary proGuard mapping files. Is there a way to control uploaded data? 

I can see that necessary files are uploaded but could not be sure that they are totally correct files.
```
 Building 64% > :app:shrinkInternalReleaseResources5% > :app:uploadBugsnagInternalReleaseMapping:app:uploadBugsnagInternalReleaseMapping
```

**Comment by cemo** [comment]
Any idea?

**Comment by loopj** [comment]
Hey @cemo we automatically upload proguard files as part of each build, so they should always be correct. Are you seeing a particular problem?

**Comment by kattrali** [comment]
Closing for lack of response, but can reopen with any new information.
