### ISSUE TITLE
7.4.1 always requires NDK to be installed, even if unused

### ISSUE THREAD

**Issue by ZacSweers** [bugsnag/bugsnag-android-gradle-plugin#503]
### Describe the bug
With the changes to make NDK dir resolution more configuration-cache friendly, it seems it's introduced a new bug where the plugin now fails at configuration-time if the NDK doesn't exist at all (which is usually the case in projects).

### Steps to reproduce
1. Update to 7.4.1 in a project that does not use the NDK
2. Configuration fails due to missing an NDK file

### Environment
* Android Studio version: N/A
* Gradle version: 7.6
* Android Gradle Plugin (AGP) version: 7.4.1
* Bugsnag Android Gradle Plugin version: 7.4.1
* Bugsnag manifest section (if modified): N/A

<details><summary>Error messages:</summary>

```

FAILURE: Build failed with an exception.
--
  |  
  | * What went wrong:
  | A problem occurred configuring project ':app'.
  | > NDK is not installed


```
</details>

**Comment by luke-belton** [comment]
Hi @ZacSweers - thanks for raising this. We're investigating and will update this thread when we know more 👍

**Comment by lemnik** [comment]
Hi @ZacSweers. I'm having trouble reproducing this issue with a fresh Android project (configured to your described Environment, with or without configuration-caching).

If I configure the project as `bugsnag.uploadNdkMappings = true` or introduce an `externalNativeBuild` path for either cmake or ndkBuild then the build produces an "NDK is not installed" error as expected, but given that projects with no NDK modules shouldn't have these configured, this doesn't seem like a valid repro to me.

Do you by any chance have a repro project that you can share?

**Comment by ZacSweers** [comment]
apologies for the delay, let me see if I can get a public repro

**Comment by ZacSweers** [comment]
Ahhh I see now, we do enable `uploadNdkMappings`. We don't have any ndk builds in our repo though, only some dependencies that use the NDK. Should we not be enabling this property in that case?

**Comment by lemnik** [comment]
Yup, sounds like you don't need it. `uploadNdkMappings` is only applicable for projects that include NDK build artefacts (and Unity). The plugin has a bit of [auto-detection code](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/09fe12b45adf0f47829ccea91613872c93518136/src/main/kotlin/com/bugsnag/android/gradle/BugsnagPlugin.kt#L582-L591) that attempts a sane-default based on whether CMake or ndkBuild are configured.

**Comment by johnkiely1** [comment]
Closing this out now, as it sounds like removing the `uploadNdkMappings` configuration should be the solution. Let us know if you have any further issues with it.

**Comment by ZacSweers** [comment]
Apologies for the delay, but closing back to say that sounds good 👍
