### ISSUE TITLE
processBugsnagDebugProguard already exists

### ISSUE THREAD

**Issue by hzsweers** [bugsnag/bugsnag-android-gradle-plugin#51]
I've been seeing this error when trying the new 3.0.0 betas (using beta2 right now)

`Error:Cannot add task ':app:processBugsnagDebugProguard' as a task with that name already exists.`

**Comment by fractalwrench** [comment]
@hzsweers thanks for the report. Are you using APK splits in your build.gradle by any chance?

**Comment by hzsweers** [comment]
Yeah I am
