### ISSUE TITLE
DexGuard 9.4+ Gradle plugin no longer has a version property

### ISSUE THREAD

**Issue by mrjameshamilton** [bugsnag/bugsnag-android-gradle-plugin#530]
### Describe the bug

The `version` field has been removed from DexGuard Gradle Plugin which means that [the version check here ](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/46cfca7e27ca61dac2af2f96a0e1032e8e7e514a/src/main/groovy/com/bugsnag/android/gradle/GroovyCompat.groovy#L42) throws a `MissingPropertyException` and then Bugsnag thinks that DexGuard is not being used.

The manifest fallback is still there when using the `path`, so the plugin could check if the property exists first.

```
        if (dexguard.hasProperty("version") && dexguard.version != null) {
            return dexguard.version
        } else {
```

But this doesn't work if the `path` option is not used i.e. DexGuard is retrieved from a Maven repository.

Additionally, detecting [earlier versions of DexGuard relied on the exception](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/46cfca7e27ca61dac2af2f96a0e1032e8e7e514a/src/main/groovy/com/bugsnag/android/gradle/GroovyCompat.groovy#L60), so this might causes issues for older versions.

### Steps to reproduce
1. Apply DexGuard plugin and Bugsnag plugin
2. Bugsnag plugin won't upload the correct mapping file because it thinks DexGuard is not being used

**Comment by johnkiely1** [comment]
Hi @mrjameshamilton, thanks for reporting. This is something we are aware of and is on our backlog to fix.   
in the meantime you can still manually upload youe dexguard mappings using our CLI https://docs.bugsnag.com/build-integrations/bugsnag-cli/upload-android-proguard

**Comment by mrjameshamilton** [comment]
Hi @johnkiely1 ! We've added the `version` field back into the DexGuard Gradle plugin which should resolve the compatibility and no changes should be required in bugsnag. It will be in DexGuard 9.4.15.

**Comment by clr182** [comment]
Hi @mrjameshamilton,
That's great, thanks for informing us! Are you happy for us to close out this ticket, or do you have any further questions?

**Comment by mrjameshamilton** [comment]
Thanks, the issue can be closed!
