### ISSUE TITLE
Task has not declared any outputs despite executing actions

### ISSUE THREAD

**Issue by rclaver** [bugsnag/bugsnag-android-gradle-plugin#541]
After building any application the only warning message is:

**Warnings**
Consider filing a bug to report this issue to the plugin developer. Generate report
 
**Always-Run Tasks**
This task runs on every build because it declares no outputs, which it must do in order to support incremental builds. Learn more 

**Recommendation:** Annotate the task output fields with one of: OutputDirectory, OutputDirectories, OutputFile, OutputFiles
**Reason task ran** Task has not declared any outputs despite executing actions.

### Full Report
At 08:38, Mar 13, 2024, Android Studio detected the following issue(s) with Gradle plugin org.jetbrains.kotlin.android

Always-Run Tasks
Task runs on every build because it declares no outputs.

Plugin: org.jetbrains.kotlin.android
Task: checkKotlinGradlePluginConfigurationErrors
Task type: org.jetbrains.kotlin.gradle.plugin.diagnostics.CheckKotlinGradlePluginConfigurationErrors
Issues for the same task were detected in 1 module(s), total execution time was <0.1s (0,1%), by module:
  Execution mode: FULL, time: <0.1s (0,1%), determines build duration: true, on critical path: false, issues: Always-Run Tasks

====Build information:====
Execution date: 13/3/24 8:38
Total build duration: 41,8s
Configuration time: 13,9s (33,2%)
Critical path tasks time: 24,3s (58,1%)
Critical path tasks size: 6
AGP versions: 8.2.2
====Platform information:====
AI-231.9392.1.2311.11330709, JRE 17.0.7+0-17.0.7b1000.6-10550314x64 JetBrains s.r.o., OS Linux(amd64) v5.15.0-100-generic, screens 1920.0x1080.0

AS: Hedgehog | 2023.1.1 Patch 2
Kotlin plugin: 231-1.9.22-release-704-AS9392.1.2311.11330709
Android Gradle Plugin: 8.2.2
Gradle: 8.2
Gradle JDK: JetBrains Runtime version 17.0.7
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)

**Comment by mclack** [comment]
Hi @rclaver 

Looking at the information you've provided, it appears that this warning message is related to the `org.jetbrains.kotlin.android` Gradle plugin, and the `checkKotlinGradlePluginConfigurationErrors` task, which indicates a possible problem with the configuration of this plugin. Please note that this warning is not related to the BugSnag Android Gradle plugin.

If you are concerned by this, we'd recommend filing a bug report to the plugin developer as suggested, or open an issue with them instead: https://github.com/JetBrains/kotlin/

As this does not look like a BugSnag problem, we are going to close this issue out. Please feel free to reopen this with additional information if you don't believe that's the case, or open a ticket with us directly by contacting support@bugsnag.com.
