### ISSUE TITLE
ApplicationID will be incorrect if it's modified during configuration

### ISSUE THREAD

**Issue by hzsweers** [bugsnag/bugsnag-android-gradle-plugin#6]
Some developers modify the application ID during build configuration, so you should create the task and resolve everything after project evalutation.

**Comment by loopj** [comment]
Hey @hzsweers thanks for the feedback. Do you happen to know of any good workarounds for this in gradle-land? Would definitely appreciate a PR if you happened to have time!

p.s. welcome to Bugsnag!

**Comment by loopj** [comment]
I think this should be fixed in #7 which we'll release as 1.2.1 of this jar.

@hzsweers can you try this pre-release jar and see if this fixes your specific issue:
https://www.dropbox.com/s/en5d2zstgdavwbg/bugsnag-android-gradle-plugin-1.2.1.jar?dl=0

**Comment by kattrali** [comment]
Fixed in release 1.2.1
