### ISSUE TITLE
Problem using latest version of Bugsnag Android Gradle Plugin

### ISSUE THREAD

**Issue by richardmuttett** [bugsnag/bugsnag-android-gradle-plugin#62]
### Expected behavior
Project should successfully sync.

### Observed behavior
Project does not sync, with the following response:
```
Error:Could not get unknown property 'packageApplication' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
```

### Steps to reproduce
Add this classpath dependency to the main project gradle settings:
 ```
classpath 'com.bugsnag:bugsnag-android-gradle-plugin:3.0.0-beta4'
 ```
Add this setting to the module's gradle settings:
 ```
apply plugin: 'com.bugsnag.android.gradle'
```

### Version
3.0.0-beta4, but also occurs with any 3+ version

### Additional information
I experimented with moving the 'apply plugin:' line to the end of the gradle file, as one set of instructions states to do, but this did not fix anything.
The project syncs successfully when I revert to version 2.4.2 but this doesn't give the extra capability wanted, to be able to auto-upload APK splits.

**Comment by fractalwrench** [comment]
@richardmuttett thanks for the report. `3.0.0-beta4` is only currently supported on the latest Android Studio Preview. Updating the Android Gradle Plugin version in your root-level build.gradle should allow you to sync gradle in Android Studio 3.0.0 Preview 2: 

`classpath 'com.android.tools.build:gradle:3.0.0-rc2'`

We'll update our docs to be a bit more explicit about this - please get in touch if you run into anything else.
