### ISSUE TITLE
Plugin is not working for AS 3.0

### ISSUE THREAD

**Issue by zoopolitic** [bugsnag/bugsnag-android-gradle-plugin#64]
```Plugin [id: 'com.bugsnag.android.gradle', version: '3.0.0'] was not found in any of the following sources:  - Gradle Core Plugins (plugin is not in 'org.gradle' namespace) - Gradle Central Plugin Repository (plugin 'com.bugsnag.android.gradle' has no version '3.0.0' - see https://plugins.gradle.org/plugin/com.bugsnag.android.gradle for available versions) Open File```

**Comment by fractalwrench** [comment]
Thanks for the report @zoopolitic - would you be able to paste the parts of your build.gradle where you're specifying the Bugsnag Plugin as a dependency?

**Comment by zoopolitic** [comment]
That was my bad, just couldn't close this issue due to github error

**Comment by fractalwrench** [comment]
No problem @zoopolitic - if you run into Github Errors again, it's possible that they're being caused by an [AdBlocker browser extension](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).

**Comment by zoopolitic** [comment]
Adblock was actually the issue :)
