### ISSUE TITLE
After updating to android-gradle-plugin 3.0.0, mapping upload does not work

### ISSUE THREAD

**Issue by redwarp** [bugsnag/bugsnag-android-gradle-plugin#66]
### Expected behavior
After doing a clean assembleRelease, and triggering a crash, the crash should be de-obfuscated

### Observed behavior
Crashes of release version remain obfuscated

### Steps to reproduce
- Update android gradle from 2.3.3 to 3.0.0
- Update bugsnag-android-gradle-plugin to 3.0.0
- run ./gradlew clean :project:assembleProdRelease

### Version
- Version 3.0.0 (both bugsnag and android plugin)
- Gradle 4.3.0

### Additional information
- Our setup use flavors
- Using curl, we tried to manually upload a mapping and then it worked just fine to deobfuscate new crashes.

**Comment by redwarp** [comment]
I did different tests:

- Mapping upload works with 3.0.0-beta2
- It is broken starting 3.0.0-beta3

**Comment by fractalwrench** [comment]
Thanks for the report @redwarp - I'll look into this right away. Are you using APK splits, and do you have any additional configuration of the Bugsnag plugin (e.g. disabling autoupload)?

Would you be able to run `./gradlew clean build` and search the output for "Attempting upload of mapping file to Bugsnag"? If the upload is successful there should be an additional messaged logged at this point.
