### ISSUE TITLE
Does it upload sourcemap like bugsnag-sourcemaps or it is proguard upload only? #question

### ISSUE THREAD

**Issue by inv2004** [bugsnag/bugsnag-android-gradle-plugin#69]
Hello,
 I did not enable pro-guard in for my release.
Question: will this plugin upload source-map (smth like here: https://github.com/bugsnag/bugsnag-sourcemaps )

Or it is just for pro-guard sources?

Thank you,

**Comment by kattrali** [comment]
Hi @inv2004, this plugin uploads ProGuard/DexGuard and NDK object mappings, not sourcemaps. For more information, see https://docs.bugsnag.com/platforms/android/mapping/

Since you did not enable ProGuard, you shouldn't need this plugin.
