### ISSUE TITLE
Problem with installation in react-native

### ISSUE THREAD

**Issue by tonygriv** [bugsnag/bugsnag-android-gradle-plugin#77]
### Expected behavior
After command react-native run-android I have a BUILD SUCCESS message

### Observed behavior

FAILURE: Build failed with an exception.

Could not find method getPackageApplication() for arguments [] on object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

### Steps to reproduce
1. Add in /android/build.gradle

`classpath 'com.bugsnag:bugsnag-android-gradle-plugin:3.+'`

In the result I have:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.bugsnag:bugsnag-android-gradle-plugin:3.+'
    }
}
```

2. Add in /android/app/build.gradle

`apply plugin: "com.bugsnag.android.gradle"`

### Version
react-native 0.51
com.android.tools.build:gradle 2.2.3

### Additional information
If I remove `apply plugin: "com.bugsnag.android.gradle"`, my project builds with success

**Comment by fractalwrench** [comment]
@tonygriv thanks for the detailed report. The Bugsnag Gradle Plugin relies on having version 3+ of the AGP installed. Following these instructions should allow you to build your project:

1. Update your gradle wrapper version to 4.1 as a minimum
`./gradlew wrapper --gradle-version 4.1`

2. In your root build.gradle file, alter the Android Gradle Plugin version to 3.+
`classpath 'com.android.tools.build:gradle:3.0.1'`, and add `
        maven { url 'https://maven.google.com' }` in the repositories closure.

3. Perform any other updates to your Gradle scripts that might be required as part of the [AGP 3 migration](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html)
